import Head from 'next/head'
import Image from 'next/image'

import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import Header from '../components/layout/Header'
// import Home from '../components/Home'

export default function Home() {
  return (
    <div className='app dark-theme'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      {/* <Home /> */}
      <Footer />
    </div>
  )
}
