import Head from 'next/head'

import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import Header from '../components/layout/Header'
import Main from '../components/Main'

export default function Home() {
  return (
    <div className='app dark-theme'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="top-border"></div>
      <Navbar />
      <Header />

      <div className={'content'}>
        <Main />
      </div>

      <Footer />
    </div>
  )
}
